package compiler;

/**
 * Created by Александр on 07.03.2016.
 */
public enum LexemeType
{
    MACHINE_INSTRUCTION,
    IDENTIFIER_32BIT_ADDRESS_REGISTER,
    IDENTIFIER_16BIT_ADDRESS_REGISTER,
    IDENTIFIER_32BIT_DATA_REGISTER,
    IDENTIFIER_16BIT_DATA_REGISTER,
    IDENTIFIER_8BIT_DATA_REGISTER,
    BYTE_USER_IDENTIFIER,
    WORD_USER_IDENTIFIER,
    DWORD_USER_IDENTIFIER,
    EQU_IDENTIFIER,
    LABEL,
    INDEFINITE,
    HEXADECIMAL_CONSTANT,
    TEXT_CONSTANT,
    ACCESS_MODIFIER,
    A_SINGLE_CHARACTER,
    SEGMENT_REGISTER,
    DIRECTIVE
}
